#! /bin/bash
#
# Inspired from 'forgit' (https://github.com/wfxr/forgit)
#
# Functions:
# 1. Utilize 'tmux popup' to show the result of 'git diff'
# 2. 'esc' to quit window created by 'tmux popup'
# -- Louis 2024/0505

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

if git rev-parse --git-dir > /dev/null 2>&1; then

  # Ensure something different
  if [ $(git diff $@ | wc -l) == 0 ]; then
    echo -e "${GREEN}No different section found...${NC}"
    exit 0 
  fi
  
  # Check if in a tmux session, if not falback to normal
  if [ -z "$TMUX" ]; then
      git diff $@
  
  else
    _WIDTH=$(tmux display-message -p '#{window_width}')
  
    if [ $_WIDTH -ge 200 ]; then
      # Weird way to round the result...
      _TPWIDTH=$(echo "scale=0; ($_WIDTH * 0.85 + 0.5)/1" | bc)
  
      # Round to the nearest even integer
      # And shrink '$_TPWIDTH' a bit to prevent unnecessary line-wrap in 'delta'
      if [ $((_TPWIDTH % 2)) -ne 0 ]; then
        _TPWIDTH=$((_TPWIDTH - 3))
  
      else
        _TPWIDTH=$((_TPWIDTH - 4))
  
      fi
  
      #echo $_TPWIDTH
      tmux popup -d "#{pane_current_path}" -h 80% -w 85% \
        -e BAT_PAGER='less -R' "git diff --color=always $@ | delta --side-by-side -w $_TPWIDTH"
  
    else
      tmux popup -d "#{pane_current_path}" -h 80% -w 85% \
        -e BAT_PAGER='less -R' "git diff --color=always $@ | delta"
  
    fi
  fi
else
  echo -e "This is${RED} NOT${NC} a git repository!"

fi
