#! /bin/bash +x
# The script iTerm executes when launching default profile
# 1. Check if default tmux session is created
# 2. If not, create and attach
# 3. If created, check if session is attached
# 4. If not attached, attach the session. If yes, no tmux command executed
# 
# If tmux is running, then
#   if $_session is there and attached then exit 
# else
#   start tmux 
# fi 
# mux $_profile 
# -- Louis 2022/0919

clear

GREEN='\033[1;32m'
NC='\033[0m'

_profile=$1
if [[ ! -f $XDG_CONFIG_HOME/tmuxinator/${_profile}.yml ]]; then 
  echo -e "Need to provide an existing tmuxinator profile"
  exit 1
fi

_session=$(yq e '.name' "$XDG_CONFIG_HOME/tmuxinator/${_profile}.yml")
_sresult=$(tmux ls -F "#{session_name}: #{session_attached}" | command grep -w ${_session} | sed -n 's/'${_session}': \([0-9]\)/\1/p')

if [[ ${_sresult} == 1 ]]; then
  echo -e "Session ${GREEN}${_session}${NC} is created and attached somewhere...\nSimply open a terminal"
  exit 0

elif [[ ${_sresult} == 0 ]]; then
  tmux attach -t ${_session}

else 
  tmuxinator ${_profile}

fi

